apiVersion: v1
kind: Service
metadata:
  name: win11-vm-00019-rdp-nodeport
  namespace: default
spec:
  ports:
    - port: 3389
      protocol: TCP
      targetPort: 3389
  selector:
    kubevirt.io/domain: win11-vm-00019
  sessionAffinity: None
  type: NodePort
